apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: s3buckets.dustbreak.com
spec:
  group: dustbreak.com
  version: v1
  scope: Namespaced
  names:
    plural: s3buckets
    singular: s3bucket
    kind: S3Bucket
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
          properties:
            name:
              type: string
        spec:
          type: object
          properties:
            name:
              type: string
            region:
              type: string
            accountId:
              type: string
          required:
            - name
            - region
            - accountId
